<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE"/>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('shopping.vn')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/tp/boo/images/favicon.png']);
//         echo '<link rel="stylesheet" href="/min/f=' . implode(',', $style) . '?1" type="text/css">';
        echo $this->headScript()//->prependFile($this->basePath() . '/tp/shopping/js/pview.js')
        						->prependFile($this->basePath() . '/js/1.10.2.min.js');
        						
        echo $this->headLink()->prependStylesheet($this->basePath() . '/tp/shopping/css/style.css')
       						  ->prependStylesheet($this->basePath() . '/tp/shopping/css/font.css')
        					  ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css');
        ?>
    </head>

    <body>
    <?php
    echo $this->render('layout/header');
    echo '<div id="container">';
    echo $this->content;
    echo '</div>';
    echo $this->render('layout/footer');
    ?>
    </body>
</html>