<div id="index-cart">
	<ul id="step-cart">
		
	</ul>
	<div id="ct-cart">
		<table>
			<tr>
				<td>Ảnh</td>
				<td>Thông tin</td>
				<td>Đơn giá</td>
				<td>Số lượng</td>
				<td>Thành tiền</td>
			</tr>
			<tr>
				<td>Ảnh</td>
				<td>Áo sơ mi</td>
				<td>200,000 vnđ</td>
				<td>
					<select>
						<option>1</option>
						<option>2</option>
					</select>
				</td>
				<td>200,000 vnđ</td>
			</tr>
			<tr>
				<td style="text-align: right;">
					<p>Tổng cộng</p>
					<p>
						<a href="">Mua sản phẩm khác</a>
						<a href="">Mua ngay</a>
					</p>
				</td>
			</tr>
		</table>
	</div>
</div>