<ul class="navigation-menu">
    <?php
    $a = explode('/', $this->UriParams()->getRequest()->getRequestUri());
    echo renderMenu($this->container, $a);
    ?>
</ul>

<?php

function renderMenu($container, $a) {
    $helper = new \Zend\View\Helper\Navigation\Menu();
    foreach ($container as $menu) {
        if ($helper->accept($menu)){
            $class = 'has-submenu';
            if($a){
                $attr = null;
                if(in_array($menu->module, $a)){
//                    $class = 'open';
//                    $attr = 'display: block';
                }
            }
            echo '<li class="'.$class.'" >';
            echo '<a href="'.$menu->getHref().'">'.$menu->icon.$menu->label.'</a>';
            if (!empty($menu->pages)) {
                echo '<ul class="submenu">';
                echo renderMenu($menu->pages, null);
                echo '</ul>';
            }
            echo '</li>';
        }
    }
}