<?php echo $this->doctype(); ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="assets/images/favicon_1.ico">

    <title>Admin manager content</title>
    <?php
    echo $this->headLink()
        ->prependStylesheet('/assets/css/responsive.css')
        ->prependStylesheet('/assets/css/menu.css')
        ->prependStylesheet('/assets/css/pages.css')
        ->prependStylesheet('/assets/css/icons.css')
        ->prependStylesheet('/assets/css/components.css')
        ->prependStylesheet('/assets/css/core.css')
        ->prependStylesheet('/assets/css/bootstrap.min.css')
        ->prependStylesheet('/assets/plugins/morris/morris.css');

//    echo $this->headScript()
//        ->prependFile('/js/admin/product/import.js');
    ?>

</head>

<body>

<?= $this->render("layout/admin_head") ?>
<div class="wrapper">
    <div class="container">
        <?= $this->content; ?>

        <footer class="footer text-right">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6">
                        © 2016. All rights reserved.
                    </div>
                    <div class="col-xs-6">
                        <ul class="pull-right list-inline m-b-0">
                            <li>
                                <a href="#">About</a>
                            </li>
                            <li>
                                <a href="#">Help</a>
                            </li>
                            <li>
                                <a href="#">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>


</body>
</html>
