<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div>
                    <h2 class="title2">Liên hệ</h2>
                    <p>
                        <b>TP Hồ Chí Minh</b>
                        41 - 47 Đông Du, Quận 1, TP Hồ Chí Minh, Việt Nam.<br/>
                        KOKOIS - 24 Thảo Điền, Quận 2, TP Hồ Chí Minh, Việt Nam.<br/>
                    </p>
                    <p>
                        <b>Hà Nội</b>
                        Kstore | 367 Kim Mã, Quận Ba Đình, Hà Nội<br/>
                        <b>Hội An</b>
                        16 Nguyễn Thái Học, phường Minh An, Thành phố Hội An.<br/>
                    </p>
                    <p>
                        <b>Sân bay</b>
                        Sân bay : Tân Sơn Nhất, Nội Bài, Phú Bài.<br/>
                        Telephone: (+84) 909 018 863.<br/>
                    </p>
                    <p>
                        <b>UK | REPRESENTATIVE CONTACT</b>
                        TEL.: (44) 776798 3143<br/>
                        Email: hoanganh@anhluong.com<br/>
                    </p>
                    <p>
                        <b>SINGAPORE | REPRESENTATIVE BY LEATHERBACKS COMPANY</b>
                        ADD.: 8 Kaki Bukit Avenue 4, Premier at Kaki Bukit, #08-21, Singapore 415875
                    </p>
                </div>
            </div>
            <div class="col-md-2">
                <h2 class="title2">Thông tin</h2>
                <ul>
                    <li><a href="">Sản phẩm</a></li>
                    <li><a href="">Giới thiệu</a></li>
                    <li><a href="">Site Map</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <h2 class="title2">Tài khoản</h2>
                <ul>
                    <li><a href="">Tài khoản của tôi</a></li>
                    <li><a href="">Thông tin cá nhân</a></li>
                    <li><a href="">Lịch sử mua hàng</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <h2 class="title2">Hỗ trợ</h2>
                <ul>
                    <li><a href="">Chính sách</a></li>
                    <li><a href="">Điều khoản và quy định</a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <p>© 2015 Bản quyền thuộc về Cincinati Leather Boutique.</p>
            </div>
            <div class="col-md-6">
                <div class="social">
                    <a class="fb" href=""></a>
                    <a class="tw" href=""></a>
                    <a class="it" href=""></a>
                    <a class="pt" href=""></a>
                    <a class="mail" href=""></a>
                </div>
            </div>
        </div>
    </div>
</div>