<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="stylesheet" id="Open_Sans_sub-css" href="//fonts.googleapis.com/css?family=Open+Sans%3A200%2C300%2C400%2C400italic%2C700&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen" />
        <?php
        echo $this->headTitle('Fashion')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/tp/boo/images/favicon.png']);
        $cs = [
            '/tp/F004/css/bootstrap.css',
            '/tp/F004/css/font-awesome.min.css',
            '/tp/F004/css/owl.carousel.css',
            '/tp/F004/css/owl.theme.css',
            '/tp/F004/css/owl.transitions.css',
            '/tp/F004/css/h.css',
        ];
        echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/tp/F004/js/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        ?>

    </head>

    <body>
        <div class="w1230">
            <?php
                echo $this->render('layout/header');
                echo $this->content;
                echo $this->render('layout/footer');
            ?>
        </div>
    </body>
    <?php
        $r = [
            '/tp/F004/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/tp/F004/js/bootstrap.min.js',
            '/tp/F004/js/jquery.lazyload.min.js',
            '/tp/F004/js/owl.carousel.js',
            '/tp/F004/js/jquery-ui-1.10.3.custom.min.js',
            '/tp/F004/js/a.js'
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,3).'"></script>';
    ?>
</html>