<div class="head">
    <div class="head1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <ul class="account">
                        <li>
                            <a>Tài khoản</a>
                            <ul>
                                <li><a href="">Tài khoản</a></li>
                                <li><a href="">Thanh toán</a></li>
                                <li><a href="">Sản phẩm yêu thích</a></li>
                            </ul>
                        </li>
                        <?php
                            if ($this->user()->hasIdentity()) {
                                ?>
                                <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a>
                                <a href="/user/signout">Thoát</a>
                                </li>
                            <?php
                                }else{
                            ?>
                                <li><a href="/user/signup">Đăng ký</a>/<a href="/user/signin">Đăng nhập</a></li>
                        <?php
                            }
                        ?>
                    </ul>
                </div>
                <div class="col-md-6">
                    <ul class="cart">
                        <?php
                            $cartService = $this->cart()->getServiceCart();
                            $products = $cartService->getProducts();
                        ?>
                        <li><a href="/cart"><?= $cartService->getTotalProducts() ?> Sản phẩm - <span><?= number_format($cartService->getTotalMoney()) ?> đ</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="head2">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a class="logo" href="/"><img src="http://cincinati.com.vn/skin/frontend/smartwave/granada/images/media/logo.png" alt="Fashion" /></a>
                </div>
                <div class="col-md-6">
                    <a id="menuMobile">
                        <i class="fa fa-reorder" aria-hidden="true"></i>
                    </a>
                    <div class="navHome">
                        <?php
                        $menu = $this->home()->menu(['positionId' => 1]);
                        if($menu){
                            ?>
                            <ul>
                                <?php
                                foreach($menu as $m){
                                    ?>
                                    <li><a href="<?= $m->getUrl() ?>"><?= $m->getName(); ?></a></li>
                                <?php
                                }
                                ?>
                            </ul>
                        <?php
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="formSearch">
                        <form id="search" action="/search" method="get">
                            <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                            <a onclick="document.getElementById('search').submit();"></a>
                            <div id="searchFolding"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="sideBar">

</div>
