<?php
$results = $this->results;
// echo $this->headLink()->appendStylesheet('js/cloudzoom/cloudzoom.css');
// echo $this->headScript()->appendFile('js/cloudzoom/cloudzoom.js');
?>
<link rel="stylesheet" type="text/css" href="/js/cloudzoom/cloudzoom.css"/>
<script type="text/javascript" src="/js/cloudzoom/cloudzoom.js"></script>
<script type="text/javascript" src="/tp/shopping/js/pview.js"></script>
<script type="text/javascript" src="/js/jquery.carouFredSel-6.2.1-packed.js"></script>
