<?php
    $category = $this->category;
    $this->headTitle($this->escapeHtml($this->translate(html_entity_decode($category->getName()))));
    $this->headMeta()->appendName('description', (html_entity_decode($category->getName())));
    $this->headMeta()->appendName('keywords', (html_entity_decode($category->getName())));
    $this->headMeta()->appendProperty('og:title', html_entity_decode($category->getName()));
    $product = $this->paginator;
    $product->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 20);

    $prodCategory = $this->category();
?>
<div class="main">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php
            if($category->getParentId()){
                $cc = $prodCategory->getId($category);
                if($cc->getParentId()){
                    $ccc = $prodCategory->getId($cc);
                    if($ccc->getParentId()){
                        $cccc = $prodCategory->getId($ccc);
                    }
                }
            }
            ?>
            <ul class="breadcrumb">
                <li><a href="/">Trang chủ</a></li>
                <?= (isset($cccc) ? '<li><a href="'.$cccc->getViewLink().'">'.$cccc->getName().'</a></li>':null) ?>
                <?= (isset($ccc) ? '<li><a href="'.$ccc->getViewLink().'">'.$ccc->getName().'</a></li>':null) ?>
                <?= (isset($cc) ? '<li><a href="'.$cc->getViewLink().'">'.$cc->getName().'</a></li>':null) ?>
                <li><a href="<?= $category->getViewLink(); ?>"><?= $category->getName(); ?></a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <div class="left">
                <h2>Danh mục</h2>
                <?php
                    $cs = [
                        '/tp/F003/css/p.css'
                    ];
                    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
                ?>
                <ul class="categoryProduct">
                    <?php
                    $categorys = $this->category()->getCategories();
                    if(count($categorys)){
                        foreach($categorys as $c){
                            ?>
                            <li <?= ($c->getChilds() ? 'class="navIsset"':null) ?>>
                            <a href="<?= $c->getViewLink() ?>"><?= $c->getName() ?></a>
                            <?php
                            if($c->getChilds()){
                                echo '<ul class="nav2">';
                                foreach($c->getChilds() as $cc){
                                    ?>
                                    <li><a href="<?= $cc->getViewLink() ?>"><?= $cc->getName() ?></a></li>
                                <?php
                                }
                                echo '</ul>';
                            }
                            ?>
                            </li>
                        <?php
                        }
                    }
                    ?>
                </ul>

                <div class="box">
                    <h1>Giá <?= (isset($this->price) ? '<a href="'.$this->product()->removeFilter('price').'" title="Xóa lựa chọn Giá">x</a>':null)  ?></h1>
                    <ul>
                        <?php
                        $this->product()->removeFilter('price');
                        $price = [];
                        if (is_array($this->price)) {
                            $price = $this->price;
                        }
                        if (in_array(array(0, 100000), $price)) {
                            echo '<li><a rel="nofollow" href="' . $this->product()->removeFilter('price', '0:100000') . '"><i class="fa fa fa-circle" aria-hidden="true"></i>Dưới 100k</a></li>';
                        }else{
                            echo '<li><a rel="nofollow" href="' . $this->product()->addFilter('price', '0:100000') . '"><i class="fa fa-circle-thin" aria-hidden="true"></i>Dưới 100k</a></li>';
                        }
                        if (in_array(array(100000, 200000), $price)) {
                            echo '<li><a href="' . $this->product()->removeFilter('price', '100000:200000') . '"><i class="fa fa fa-circle" aria-hidden="true"></i>Từ 100k - 200k</a></li>';
                        }else{
                            echo '<li><a href="' . $this->product()->addFilter('price', '100000:200000') . '"><i class="fa fa-circle-thin" aria-hidden="true"></i>Từ 100k - 200k</a></li>';
                        }
                        if (in_array(array(200000, 300000), $price)) {
                            echo '<li><a href="' . $this->product()->removeFilter('price', '200000:300000') . '"><i class="fa fa fa-circle" aria-hidden="true"></i>Từ 200k - 300k</a></li>';
                        }else{
                            echo '<li><a href="' . $this->product()->addFilter('price', '200000:300000') . '"><i class="fa fa-circle-thin" aria-hidden="true"></i>Từ 200k - 300k</a></li>';
                        }
                        if (in_array(array(300000, 400000), $price)) {
                            echo '<li><a href="' . $this->product()->removeFilter('price', '300000:400000') . '"><i class="fa fa fa-circle" aria-hidden="true"></i>Từ 300k - 400k</a></li>';
                        }else{
                            echo '<li><a href="' . $this->product()->addFilter('price', '300000:400000') . '"><i class="fa fa-circle-thin" aria-hidden="true"></i>Từ 300k - 400k</a></li>';
                        }
                        if (in_array(array(400000, 500000), $price)) {
                            echo '<li><a href="' . $this->product()->removeFilter('price', '400000:500000') . '"><i class="fa fa fa-circle" aria-hidden="true"></i>Từ 400k - 500k</a></li>';
                        }else{
                            echo '<li><a href="' . $this->product()->addFilter('price', '400000:500000') . '"><i class="fa fa-circle-thin" aria-hidden="true"></i>Từ 400k - 500k</a></li>';
                        }
                        if (in_array(array(500000), $price)) {
                            echo '<li><a href="' . $this->product()->removeFilter('price', '500000') . '"><i class="fa fa fa-circle" aria-hidden="true"></i>Trên 500k</a></li>';
                        }else{
                            echo '<li><a href="' . $this->product()->addFilter('price', '500000') . '"><i class="fa fa-circle-thin" aria-hidden="true"></i>Trên 500k</a></li>';
                        }
                        ?>
                    </ul>
                </div>

                <div class="box">
                    <h1>Màu <?= (isset($this->requestColor) ? '<a href="'.$this->product()->removeFilter('color').'" title="Xóa lựa chọn Color">x</a>':null)  ?></h1>
                    <?php
                    $request = $this->requestColor;
                    $requests = explode(',',$request);
                    $attr = $this->home()->getAttr(['type' => 1, 'group' => true]);
                    if(count($attr)){
                        echo '<ul class="attr">';
                        foreach($attr as $at){
                            if(in_array($at->getProductAttrId(),$requests)){
                                echo '<li><a class="active" href="' . $this->product()->removeFilter('color', $at->getProductAttrId()) . '" style="background-color: '.$at->getColorCode().'" title="'.$at->getName().'"></a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('color', $at->getProductAttrId()) . '" style="background-color: '.$at->getColorCode().'" title="'.$at->getName().'"></a></li>';
                            }
                        }
                        echo '</ul>';
                    }
                    ?>
                </div>

                <div class="box">
                    <h1>Size <?= (isset($this->requestSize) ? '<a href="'.$this->product()->removeFilter('size').'" title="Xóa lựa chọn Size">x</a>':null)  ?></h1>
                    <?php
                    $request = $this->requestSize;
                    $requests = explode(',',$request);
                    $attr = $this->home()->getAttr(['type' => 2, 'group' => true]);
                    if(count($attr)){
                        echo '<ul class="attr">';
                        foreach($attr as $at){
                            if(in_array($at->getProductAttrId(),$requests)){
                                echo '<li><a href="' . $this->product()->removeFilter('size', $at->getProductAttrId()) . '" class="active" title="'.$at->getName().'">'.$at->getName().'</a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('size', $at->getProductAttrId()) . '" title="'.$at->getName().'">'.$at->getName().'</a></li>';
                            }
                        }
                        echo '</ul>';
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="right">
                <div class="productCategory">
                    <?php
                        $show = $this->request->getQuery('show');
                        if(count($product)){
                            echo '<div class="titlePaginator">';
                            echo '<h1 class="title">'.$category->getName().'</h1>';
                            echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPageRemmy');
                            echo '</div>';
                            echo '<ul class="lPC">';
                            foreach($product as $p){
                                $images = $this->home()->getImages(['id' => $p->getId(), 'type' => 2]);
                                $img = '';
                                $img1 = '';
                                if(count($images)){
                                    $c = 0;
                                    foreach($images as $i){
                                        $c++;
                                        if($c == 1){
                                            $img = '<img class="img1 lazy" src="/tp/F003/img/grey.gif" data-original="'.$i->getOption('media')->getPictureUri().'" alt="'.$p->getName().'" />';
                                        }elseif($c == 2){
                                            $img1 = '<img class="img2 lazy" src="/tp/F003/img/grey.gif" data-original="'.$i->getOption('media')->getPictureUri().'" alt="'.$p->getName().'" />';
                                        }
                                    }
                                }
                                echo '<li>
                                        <a class="pI" href="../'.$p->getViewLink().'">'.$img.$img1.'</a>
                                        <h2><a href="../'.$p->getViewLink().'">'. $p->getName().'</a></h2>
                                        <p '.($p->getPriceOld() ? 'class="oldPrice"':'').'>'.($p->getPriceOld() ? '<span>'.number_format($p->getPriceOld()).'₫</span><i>'.number_format($p->getPrice()).'₫</i>':number_format($p->getPrice()).'₫').'</p>
                                    </li>';
                            }
                            echo '</ul>';
                            echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPageRemmy');
                        }else{
                            echo '<p style="margin: 10px 0 0 0;text-align: center">Đang được cập nhật</p>';
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
</div>