<?php
    $c = $this->category;
    $this->headTitle($this->escapeHtml($this->translate($c->getName())));
    $this->headMeta()->appendName('description', ($c->getDescription() ? : $c->getDescription()));
    $this->headMeta()->appendName('keywords', ($c->getName() ? : $c->getName()));
    $this->headMeta()->appendProperty('og:title', $c->getName());
?>
<div class="wrapper">
    <div class="header">
        <div class="container">
            <div class="col-md-12">
                <div class="logo">
                    <a href="/" title="Differrence Web"><img src="/tp/dweb/image/dweb.png" alt="Differrence Web" /></a>
                </div>
            </div>
        </div>
    </div>
    <div class="main">
        <?php
            echo $this->render('layout/about');
        ?>
        <div class="container">
            <div class="col-md-12">
                <div class="blog">
                    <?php
                    if(count($this->paginator)){
                        ?>
                        <ul>
                            <?php
                            foreach($this->paginator as $n){
                                $like = $this->home()->getLike(['id' => $n->getId(), 'type' => 1]);
                                ?>
                                <li>
                                    <a href="<?= $n->getViewLink() ?>">
                                        <img src="<?= $n->getPictureUri() ?>" alt="<?= $n->getTitle() ?>" />
                                    </a>
                                    <div>
                                        <span><?= date('d/m/Y', strtotime($n->getCreatedDateTime())) ; ?></span>
                                        <h2><a href="<?= $n->getViewLink() ?>"><?= $n->getTitle() ?></a></h2>
                                    </div>
                                </li>
                            <?php
                            }
                            ?>
                            <div class="clear"></div>
                        </ul>
                    <?php
                    }
                    ?>
                    <?php
                        echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                    ?>
                </div>
            </div>
        </div>
    </div>

    <!---------End main ---------->