<div class="wrapper">
    <div class="header">
        <div class="container">
            <div class="col-md-12">
                <div class="logo">
                    <a href="/" title="Differrence Web"><img src="/tp/dweb/image/dweb.png" alt="Differrence Web" /></a>
                </div>
            </div>
        </div>
    </div>


    <div class="main">
        <?php
            echo $this->render('layout/about');
        ?>
        <div class="profilo">
            <?php
            $a =  $this->paginator;

//            $new = $this->news()->searchArticle(['type' => 1]);
            if(count($a)){
                ?>
                <ul>
                    <?php
                    foreach($a as $n){
                        $like = $this->home()->getLike(['id' => $n->getId(), 'type' => 1]);
                        $images = $this->home()->getImages(['id' => $n->getId(), 'type' => 1]);

                        ?>
                        <li>
                            <a href="<?= $n->getViewLink() ?>">
                                <?php
                                if(count($images)){
                                    $c = 0;
                                    foreach($images as $i){
                                        $c++;
                                        if($c == 1){
                                            echo '<img src="'.$i->getOption('media')->getPictureUri().'" alt="'.$n->getTitle().'" />';
                                        }
                                    }
                                }
                                ?>
                                <div class="overlay">
                                    <summary>
                                        <h2><?= $n->getTitle() ?></h2>
                                        <h3>Identity, Website &amp; Photography</h3>
                                    </summary>
                                    <div class="loves"><span><?= $like ?></span></div>
                                </div>
                            </a>
                        </li>
                    <?php
                    }
                    ?>
                    <div class="clear"></div>
                </ul>
            <?php
            }
            ?>
            <?php
                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
            ?>
        </div>
    </div>