<section class="to-top">
    <div class="container">
        <div class="row">
            <div class="to-top-wrap">
                <a href="#top" class="top"><i class="fa fa-angle-up"></i></a>
            </div>
        </div>
    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="footer-links">
                    <ul class="footer-group">
                        <li><a href="#">Trang chủ</a></li>
                        <li><a href="#">Bảng giá</a></li>
                        <li><a href="#">Dự án hoàn thành</a></li>
                        <li><a href="#">Blog</a></li>
                    </ul>
                    <p>Copyright © 2015 <a href="#">Cut HTML/CSS</a><br>
                        Một sản phẩm | <a href="">DWEB</a> | Author by <a href="http://dweb.vn">Mienlv</a></p>
                </div>
            </div>
            <div class="social-share">
                <p>Kết nối với chúng tôi</p>
                <a href="https://twitter.com/peterfinlan" class="twitter-share"><i class="fa fa-twitter"></i></a> <a href="#" class="facebook-share"><i class="fa fa-facebook"></i></a>
            </div>
        </div>
    </div>
</footer>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cảnh báo</h4>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>

    </div>
</div>