<body id="top">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<section class="hero">
    <section class="navigation">
        <header>
            <div class="header-content">
                <div class="logo"><a href="#"><h1><span>Cut</span>htmlcss</h1></a></div>
                <div class="header-nav">
                    <nav>
                        <ul class="primary-nav">
                            <li><a href="#features">Bảng giá</a></li>
                            <li><a href="#assets">Dự án hoàn thành</a></li>
                            <li><a href="#blog">Blog</a></li>
                        </ul>
                        <ul class="member-actions">
                            <li><a href="#download" class="btn-white btn-small">Gửi bản thiết kế</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="navicon">
                    <a class="nav-toggle" href="#"><span></span></a>
                </div>
            </div>
        </header>
    </section>