<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Trang chủ | Cut HTML/CSS')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/tp/boo/images/favicon.png']);

        echo $this->headLink()->prependStylesheet($this->basePath() . 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
                              ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/animate.min.css')
                              ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/etline-font.css')
                              ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/queries.css')
                              ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/styles.css')
                              ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/flexslider.css')
                              ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/jquery.fancybox.css')
       						  ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/bootstrap.min.css')
        					  ->prependStylesheet($this->basePath() . '/tp/cuthtmlcss/css/normalize.min.css');

        echo $this->headScript()->prependFile($this->basePath() . '/tp/cuthtmlcss/js/modernizr-2.8.3-respond-1.4.2.min.js');
        ?>
    </head>

    <body>
    <?php
        echo $this->render('layout/header');
        echo $this->content;
        echo $this->render('layout/footer');
    ?>
    </body>
    <?php
        echo $this->headScript()->prependFile($this->basePath() . '/tp/cuthtmlcss/js/jquery.waypoints.min.js')
            ->prependFile($this->basePath() . '/tp/cuthtmlcss/js/classie.js')
            ->prependFile($this->basePath() . '/tp/cuthtmlcss/js/jquery.flexslider-min.js')
            ->prependFile($this->basePath() . '/tp/cuthtmlcss/js/scripts.js')
            ->prependFile($this->basePath() . '/tp/cuthtmlcss/js/vendor/bootstrap.min.js')
            ->prependFile($this->basePath() . '/tp/cuthtmlcss/js/jquery.fancybox.pack.js')
            ->prependFile($this->basePath() . '/tp/cuthtmlcss/js/retina.js')
            ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js');
    ?>
</html>