<div class="head">
    <div class="head1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2><i class="fa fa-phone"></i> Tư vấn hỗ trợ: 19002008</h2>
                </div>
                <div class="col-md-6">

                    <ul class="RegisterLogin">
                        <?php
                        $cartService = $this->cart()->getServiceCart();
                        $products = $cartService->getProducts();
                        ?>
                        <li><a class="totalCart" href="/cart"><span><?= $cartService->getTotalProducts() ?></span></a></li>
                        <li><a href="/news"><i class="fa fa-book"></i>Tin tức</a></li>
                        <li><a href="/news">Hỗ trợ và hỏi đáp</a>
                            <ul>
                                <li><a href="">Tin tức 1</a></li>
                                <li><a href="">Tin tức 2</a></li>
                                <li><a href="">Tin tức 3</a></li>
                            </ul>
                        </li>

                        <?php
                        if ($this->user()->hasIdentity()) {
                            ?>
                            <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                            <li><a href="/user/signout">Thoát</a></li>
                        <?php
                        }else{
                            ?>
                            <li><a href="/user/signup">Tạo tài khoản mới</a></li>
                            <li><a href="/user/signin">Đăng nhập</a></li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="head2">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a class="logo" href="/">
                        <img src="/tp/T001/img/logo.png" alt="Logo" />
                    </a>
                </div>
                <div class="col-md-6">
                    <form id="search" action="/search" method="get">
                        <input type="text" name="q" placeholder="Tìm kiếm sản phẩm bạn muốn mua tại đây"/>
                        <p><strong>Từ khóa phổ biến:</strong> <a href="/search?q=iphone 5s">iphone 5s</a> <a href="/search?q=ốp lưng điện thoại">ốp lưng điện thoại</a> <a href="/search?q=áo sơ mi">áo sơ mi</a> <a href="/search?q=áo thun">áo thun</a></p>
                        <a href="javascript:{}" onclick="document.getElementById('search').submit();"></a>
                        <div id="searchFolding"></div>
                    </form>
                </div>
                <div class="col-md-3">

                </div>
            </div>
        </div>
    </div>
    <div class="head3">
        <div class="container">
            <div class="row">
            <div class="col-md-12">
                <div class="CategoryShip">
                    <div class="categoryHome">
                        <h2>Danh mục sản phẩm <i class="fa fa-bars"></i></h2>
                        <div class="nav" >
                            <?php
                            $category = $this->category()->getCategories();
                            ?>
                            <ul>
                                <?php
                                if(count($category)){
                                    foreach($category as $c){
                                        ?>
                                        <li>
                                        <a href="<?= $c->getViewLink() ?>"><i class="fa fa-angle-right"></i><?= $c->getName() ?></a>
                                        <?php
                                        if($c->getChilds()){
                                            echo '<ul class="nav2">';
                                            echo '<h3>'.$c->getName().'</h3>';
                                            foreach($c->getChilds() as $cc){
                                                ?>
                                                <li><a href="<?= $cc->getViewLink() ?>"><?= $cc->getName() ?></a>
                                                <?php
                                                if($cc->getChilds()){
                                                    echo '<ul class="nav3">';
                                                    foreach($cc->getChilds() as $ccc){
                                                        ?>
                                                        <li><a href="<?= $ccc->getViewLink() ?>"><?= $ccc->getName() ?></a></li>
                                                    <?php
                                                    }
                                                    echo '</ul>';
                                                }
                                                ?>
                                                </li>
                                            <?php
                                            }
                                            echo '</ul>';
                                        }
                                        ?>
                                        </li>
                                    <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>

                    <div class="ShipOption">
                        <ul>
                            <li><a href="">Giao hàng toàn quốc</a></li>
                            <li><a href="">Miễn phí vận chuyển nội thành Hà Nội</a></li>
                            <li><a href="">Đổi trả trong 3 ngày</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        </div>
    </div>
</div>