<link rel="stylesheet" type="text/css" href="css/banner.css" />
<script type="text/javascript" src="js/modernizr.custom.53451.js"></script>
<script type="text/javascript" src="js/jquery.gallery.js"></script>
<script type="text/javascript">
			$(function() {
				$('#dg-container').gallery({
					autoplay	:	true,
					interval	: 6000,
				});
			});
</script>
<div id="banner">
	<div id="bn">
			<section id="dg-container" class="dg-container">
				<div class="dg-wrapper">
					<a href="#"><img src="images/imgbanner/1.jpg" alt="image01"></a>
					<a href="#"><img src="images/imgbanner/2.jpg" alt="image02"></a>
					<a href="#"><img src="images/imgbanner/3.jpg" alt="image03"></a>
					<a href="#"><img src="images/imgbanner/4.jpg" alt="image04"></a>
					<a href="#"><img src="images/imgbanner/5.jpg" alt="image05"></a>
					<a href="#"><img src="images/imgbanner/6.jpg" alt="image06"></a>
					<a href="#"><img src="images/imgbanner/7.jpg" alt="image07"></a>
					<a href="#"><img src="images/imgbanner/8.jpg" alt="image08"></a>
					<a href="#"><img src="images/imgbanner/9.jpg" alt="image09"></a>
					<a href="#"><img src="images/imgbanner/10.jpg" alt="image10"></a>
				</div>
				<nav>
					<span class="dg-prev">&gt;</span>
					<span class="dg-next">&lt;</span>
				</nav>
			</section>
	</div>
</div>
