<div id="footer">
	<div id="ct-footer">
		<div id="bt-down">
			
		</div>
		<div id="list-ct-ft">
			
			<div id="tv" style="margin-left: 0">
				<h3>Liên hệ với chúng tôi</h3>
				<ul>
					<li><a href="">Thiết kế website chuyên nghiệp số 1 tại Việt Nam</a></li>
					<li><a href="">Địa chỉ: 67- Yên Sở - Hoàng Mai - Hà Nội</a></li>
					<li><a href="">Điện thoại: 01676.274.056</a></li>
					<li><a href="">Email: truonghonghoangtbkx@gmail.com</a></li>
				</ul>
			</div>
			<div id="tv">
				<h3>Tư vấn cho bạn</h3>
				<ul>
					<li><a href="">Giới thiệu TinhhoaWeb</a></li>
					<li><a href="">Tính năng nổi bật</a></li>
					<li><a href="">Kho giao diện</a></li>
					<li><a href="">Bảng giá</a></li>
					<li><a href="">Trợ giúp</a></li>
					<li><a href="">Hình thức thanh toán</a></li>
				</ul>
			</div>
			<div id="tv" class="suport-ft">
				<img alt="" src="/images/us_sp.jpg" class="img-us-sp">
				<p id="sp-ft-name">Huy Hoàng</p>
				<p>Tư vấn - <span>01676.274.056</span></p>
				<p>
	                 <a class="skype" href="skype:hoang_tin3a2?chat">
	                     <img src="/images/skype-icon.png" alt="">
	                 </a> 
	                 <a class="yahoo" href="ymsgr:SendIM?langtutinhtruong_1314">
	                      <img src="http://opi.yahoo.com/online?u=langtutinhtruong_1314&amp;m=g&amp;t=1&amp;l=us" alt="">
	                 </a>
				</p>
			</div>
			<div id="tv" class="signin">
				<h3>Đăng nhập | Đăng ký</h3>
				<form action="">
					<input type="text" name="username" placeholder="Tên đăng nhập" class="sg-txt"><br>
					<input type="password" name="password" placeholder="Mật khẩu" class="sg-txt"><br>
					<input type="button" id="btsignin" value="Đăng Nhập" class="sg-bt">
					<input type="button" id="btregister" value="Đăng ký" class="sg-bt">
				</form>
			</div>
		</div>
		<div id="ft">
		<p>&copy Copyright 2014 - 2019 <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>Tinhhoaweb.vn – Giải pháp thiết kế website số 1 Việt nam</p>
		</div>
	</div>
</div>