<div id="header">
	<div id="main-logo">
		<div id="logo-ct">
			<div id="logo">
				<h1><span>T</span>inhhoaWeb</h1>
				<p id="p">Nơi gửi trọn niềm tin</p>
			</div>
			<div id="hd-right">
				<p id="contact">Thiết kế website chuyên nghiệp số 1 tại Việt Nam</p>
				<p id="line"></p>
				<p id="support">Hãy để chúng tôi tư vấn cho bạn <span><i class="fa fa-phone"></i>01676.274.056</span></p>
			</div>
		</div>
	</div>
	<div id="main-menu">
		<div id="ct-menu">
			<div id="menu">
				<ul>
					<li><a href="/">Trang chủ</a><span id="span"></span></li>
					<li id="menu_line"></li>
					<li><a href="#">Giới thiệu</a></li>
					<li id="menu_line"></li>
					<li><a href="/product">Kho giao diện</a></li>
					<li id="menu_line"></li>
					<li><a href="#">Bảng giá</a></li>
					<li id="menu_line"></li>
					<li><a href="#">Dịch vụ</a></li>
					<li id="menu_line"></li>
					<li><a href="/article">Tin tức</a></li>
				</ul>
			</div>
			<div id="cart">
			</div>
		</div>
	</div>
</div>





