<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	 <?php
  	 	echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
  	 						  ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
  	 						  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
		echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
								->prependFile($this->basePath() . '/js/bootstrap.min.js')
								->prependFile($this->basePath() . '/js/1.10.2.min.js');
	?>
  </head>

  <body>
     <?= $this->render('layout/header')?>
        <div id="wrapper">
            <div id="main-content">
              <?php echo $this->content; ?>
            </div>
        </div>
     <?= $this->render('layout/footer')?>
  </body>
  
</html>