<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="logo">
                    <a href=""></a>
                    <form method="post">
                        <input type="text" placeholder="Bạn đang tìm gì ..."/>
                        <a href="btnSearch"></a>
                    </form>
                </div>
                <div class="nav">
                    <ul>
                        <li><a href=""><i class="i-mobile"></i>Điện thoại</a></li>
                        <li><a href=""><i class="i-table"></i>Table</a></li>
                        <li><a href=""><i class="i-laptop"></i>Laptop</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>