<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?php
        echo $this->headTitle('Trang chủ')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/tp/boo/images/favicon.png']);

        echo $this->headLink()->prependStylesheet($this->basePath() . '/tp/thegioididong/css/a.css')
                              ->prependStylesheet($this->basePath() . '/tp/thegioididong/css/bootstrap.min.css');
        ?>
    </head>

    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
        ?>
    </body>
    <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/tp/thegioididong/js/a.js')
            ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js');
    ?>
</html>