<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
        <?php
            echo $this->headTitle('Food')->setSeparator(' - ')->setAutoEscape(false);
            $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
            echo $this->headMeta();

            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/tp/boo/images/favicon.png']);

            $cs = [
                '/tp/food/css/bootstrap.css',
                '/tp/food/css/font-awesome.min.css',
                '/tp/food/css/owl.carousel.css',
                '/tp/food/css/h.css',
            ];

            echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
            $js = [
                '/tp/food/js/jquery-1.11.2.min.js',
            ];
            echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        ?>

    </head>

    <body>
        <?php
            echo $this->render('layout/header');
            echo '<div class="main">';
            echo $this->content;
            echo '</div>';
            echo $this->render('layout/footer');
        ?>
    </body>
    <?php
        $r = [
            '/tp/food/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/tp/food/js/bootstrap.min.js',
            '/tp/food/js/jquery.lazyload.min.js',
            '/tp/food/js/owl.carousel.js',
            '/tp/food/js/jquery-ui-1.10.3.custom.min.js',
            '/tp/food/js/a.js'
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,3).'"></script>';
    ?>
</html>