<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?php
        echo $this->headTitle('Trang chủ')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/tp/boo/images/favicon.png']);
        echo $this->headLink()->prependStylesheet($this->basePath() . '/tp/tobao/css/a.css')
                              ->prependStylesheet($this->basePath() . '/tp/tobao/css/bootstrap.css');
        ?>
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,500&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
    </head>

    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
        ?>
    </body>

    <?php
        echo $this->headScript()
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.js')
            ->prependFile($this->basePath() . '/tp/tobao/js/a.js')
            ->prependFile($this->basePath() . '/tp/tobao/js/jquery-1.10.1.min.js');
    ?>
</html>