<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="hero-content text-center">
                <h1>PSD to HTML/CSS</h1>
                <p class="intro">Bạn đang tìm kiếm một dịch vụ cut psd to HTML/CSS tại Việt Nam. Chúng tôi luôn sẵn sàng giúp đỡ bạn, để tiết kiệm thời gian, chi phí, công nghệ. Các dịch vụ mà chúng tôi đang cung cấp PSD to HTML/CSS, PSD To Wordpress, PSD to Email, PSD to a Website</p>
                <a href="#" class="btn btn-fill btn-large ">Gửi bản thiết kế</a>
            </div>
        </div>
    </div>
</div>
<div class="down-arrow floating-arrow"><a href="#"><i class="fa fa-angle-down"></i></a></div>
</section>

<section class="intro section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-4 intro-feature">
                <div class="intro-icon">
                    <span data-icon="&#xe033;" class="icon icon-clock"></span>
                </div>
                <div class="intro-content">
                    <h5>HTML/CSS</h5>
                    <p>Chúng tôi nhận bản thiết kế của bạn sau đó chuyển bằng tay sang định dạng HTML chuẩn validate W3C, tối ưu hóa SEO, kiểm tra kỹ trên các trình duyệt</p>
                </div>
            </div>
            <div class="col-md-4 intro-feature">
                <div class="intro-icon">
                    <span data-icon="&#xe030;" class="icon icon-mobile"></span>
                </div>
                <div class="intro-content">
                    <h5>Website</h5>
                    <p>Chúng tôi sẽ cung cấp cho bạn một mã nguồn dễ dàng quản lý, giàu tính năng, dựa trên nền tảng Wordpress hoặc CMS của chúng tôi phát triển</p>
                </div>
            </div>
            <div class="col-md-4 intro-feature">
                <div class="intro-icon">
                    <span data-icon="&#xe046;" class="icon icon-chat"></span>
                </div>
                <div class="intro-content last">
                    <h5>Email</h5>
                    <p>Chúng tôi sẽ chuyển đổi thiết kế của bạn qua một mẫu email HTML, tương thích với tất cả các khách hàng với những email hiện đại</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="features section-padding" id="features">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-offset-7">
                <div class="feature-list">
                    <h3>Tại sao bạn chọn chúng tôi</h3>
                    <ul class="features-stack">
                        <li class="feature-item">
                            <div class="feature-icon">
                                <span data-icon="&#xe03e;" class="icon icon-clock"></span>
                            </div>
                            <div class="feature-content">
                                <h5>Tiết kiệm thời gian/chi phí</h5>
                                <p>Việc doanh nghiệp thuê một Developer Front End để hoàn thành dự án là điều mà doanh nghiệp phải tính toán cho chất lượng công việc, quản lý thời gian, chi phí</p>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="feature-icon">
                                <span data-icon="&#xe040;" class="icon icon-mobile"></span>
                            </div>
                            <div class="feature-content">
                                <h5>Công nghệ mới</h5>
                                <p>HTML5, CSS3, Responsive đó là những gì mà chúng tôi áp dụng cho tất cả các dự án của mình. Ngoài ra còn một số plugin được sử dụng và khai báo dõ dàng </p>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="feature-icon">
                                <span data-icon="&#xe03c;" class="icon icon-chat"></span>
                            </div>
                            <div class="feature-content">
                                <h5>Hỗ trợ Back-End</h5>
                                <p>Chúng tôi sẽ hỗ trợ kỹ thuật bạn 15 ngày kể từ ngày bàn giao để giúp bạn có thể hoàn thành dự án tốt hơn</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="device-showcase">
        <div class="devices">
            <div class="ipad-wrap wp1"></div>
            <div class="iphone-wrap wp2"></div>
        </div>
    </div>
    <div class="responsive-feature-img"><img src="../img/devices.png" alt="responsive devices"></div>
</section>
<section class="features-extra section-padding" id="assets">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="feature-list">
                    <h3>Responsive Web Design</h3>
                    <p>Theo thống kê trên thế giới hiện có khoảng 1,7 tỷ người tiêu dùng sử dụng Mobile lướt web vào thời điểm năm 2013 và phát triển mạnh trong năm 2015, và con số này ngày càng tăng.</p>
                    <p>Responsive Web là một bản web duy nhất có thể chạy được trên tất cả các thiết bị như máy tính cá nhân, smartphone, hoặc tablet.</p>
                    <p>Responsive Web có khả năng tự động thay đổi kích thước nội dung và hình ảnh cho nhiều loại kích thước màn hình khác nhau để chắc chắn rằng website đó được truy cập hiệu quả và dễ dàng trên bất kỳ thiết bị nào.</p>
                    <a href="#" class="btn btn-ghost btn-accent btn-small">Đọc tiếp</a>
                </div>
            </div>
        </div>
    </div>
    <div class="macbook-wrap wp3"></div>
    <div class="responsive-feature-img"><img src="/tp/cuthtmlcss/img/macbook-pro.png" alt="responsive devices"></div>
</section>
<section class="hero-strip section-padding" style="display: none">
    <div class="container">
        <div class="col-md-12 text-center">
            <h2>
                Customise Sedna with the included <span class="sketch">Sketch <i class="version">3</i></span> file
            </h2>
            <p>Change/swap/edit every aspect of Sedna before you hit development with the included Sketch file.</p>
            <a href="#" class="btn btn-ghost btn-accent btn-large">Download now!</a>
            <div class="logo-placeholder floating-logo"><img src="/tp/cuthtmlcss/img/sketch-logo.png" alt="Sketch Logo"></div>
        </div>
    </div>
</section>
<section class="blog-intro section-padding" id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Blog Cut HTML/CSS</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-12 col-xs-12 leftcol">
                <h5>EXCLUSIVE TO CODROPS</h5>
                <p>Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12 rightcol">
                <h5>SPREADING PIXELS AROUND THE WORLD</h5>
                <p>Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</section>
<section class="blog text-center">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <article class="blog-post">
                    <figure>
                        <a href="img/blog-img-01.jpg" class="single_image">
                            <div class="blog-img-wrap">
                                <div class="overlay">
                                    <i class="fa fa-search"></i>
                                </div>
                                <img src="/tp/cuthtmlcss/img/blog-img-01.jpg" alt="Sedna blog image"/>
                            </div>
                        </a>
                        <figcaption>
                            <h2><a href="#" class="blog-category" data-toggle="tooltip" data-placement="top" data-original-title="See more posts">Product</a></h2>
                            <p><a href="#" class="blog-post-title">Getting started with Sedna <i class="fa fa-angle-right"></i></a></p>
                        </figcaption>
                    </figure>
                </article>
            </div>
            <div class="col-md-4">
                <article class="blog-post">
                    <figure>
                        <a href="img/blog-img-02.jpg" class="single_image">
                            <div class="blog-img-wrap">
                                <div class="overlay">
                                    <i class="fa fa-search"></i>
                                </div>
                                <img src="/tp/cuthtmlcss/img/blog-img-02.jpg" alt="Sedna blog image"/>
                            </div>
                        </a>
                        <figcaption>
                            <h2><a href="#" class="blog-category" data-toggle="tooltip" data-placement="top" data-original-title="See more posts">Technology</a></h2>
                            <p><a href="#" class="blog-post-title">Why IE8 support is deminishing <i class="fa fa-angle-right"></i></a></p>
                        </figcaption>
                    </figure>
                </article>
            </div>
            <div class="col-md-4">
                <article class="blog-post">
                    <figure>
                        <a href="img/blog-img-03.jpg" class="single_image">
                            <div class="blog-img-wrap">
                                <div class="overlay">
                                    <i class="fa fa-search"></i>
                                </div>
                                <img src="/tp/cuthtmlcss/img/blog-img-03.jpg" class="single_image" alt="Sedna blog image"/>
                            </div>
                        </a>
                        <figcaption>
                            <h2><a href="#" class="blog-category" data-toggle="tooltip" data-placement="top" data-original-title="See more posts">Product</a></h2>
                            <p><a href="#" class="blog-post-title">Sedna tutorial: How to begin your <i class="fa fa-angle-right"></i></a></p>
                        </figcaption>
                    </figure>
                </article>
            </div>
            <a href="#" class="btn btn-ghost btn-accent btn-small">More news</a>
        </div>
    </div>
</section>
<section class="sign-up section-padding text-center" id="download">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h3>Gửi yêu cầu của bạn cho chúng tôi</h3>
                <p>Tài khoản này có thể sử dụng để đăng nhập thành viên</p>
                <form class="signup-form" action="#" enctype="multipart/form-data" method="POST" role="">
                    <div class="form-input-group">
                        <i class="fa fa-envelope"></i><input type="email" class="email" placeholder="Email" name="name">
                    </div>
                    <div class="form-input-group">
                        <i class="fa fa-phone"></i><input type="text" class="phone" placeholder="Điện thoại" name="phone">
                    </div>
                    <div class="form-input-group">
                        <i class="fa fa-link"></i><input type="text" class="url" placeholder="Đường dẫn file" name="url">
                    </div>
                    <p style="padding: 0 0;margin: 0 0 10px 0;"><span>Hoặc</span></p>
                    <div class="form-input-group">
                        <i class="fa fa-file"></i><input type="file" id="file" class="" placeholder="File" name="file">
                    </div>
                    <a class="btn-fill sign-up-btn">Gửi</a>
                </form>
            </div>
        </div>
    </div>
</section>