<div class="container1">
    <div class="sologan">
        <p>
            Xin chào. DWEB là một đội ngũ với những con người trẻ đầy nhiệt huyết và sáng tạo trong công việc chúng tôi đã có những năm tháng làm việc ở những môi trường khác nhau và những công ty lớn trước khi có một sản phẩm mang tên DWEB
        </p>
        <div class="more">
            <p>
                DWEB được viết tắt trong từ Difference Web, chúng tôi áp dụng những kỹ năng, sự khéo léo và tỉ mỉ đến từng dự án và phấn đấu để cung cấp giải pháp thiết kế sáng tạo, luôn muốn mang đến sự trải nghiệm khách hàng trong những sản phẩm mà chúng tôi tạo nên, từ những bản thiết kế, những dòng code sáng, điểm ảnh hoàn hảo trong style, sự đơn giản trong Website mà vẫn đảm bảo được người dùng có những trải nghiệm trực quan khi sử dụng
            </p>
            <p>
                Tại sao bạn chọn chúng tôi ? Thiết kế và phát triển trang web là cốt lõi của kinh doanh của chúng tôi. Chúng tôi tin tưởng, thiết kế trang web đơn giản mạnh mẽ và chất lượng xây dựng làm việc hài hòa để tạo ra một trải nghiệm người dùng đáng nhớ. Trái ngược với nhiều cơ quan khác, chúng tôi đặt trọng tâm vào sự sáng tạo, thiết kế, chuyển hướng nội dung và dễ sử dụng. Chúng tôi âu yếm thủ công tất cả các trang web của chúng tôi bằng tay, sử dụng các tiêu chuẩn công nghệ web mới nhất và và sử dụng mã nguồn mà chúng tôi tự phát triển giúp website nhẹ cho việc tải trang nhanh hơn và lập chỉ mục tốt hơn bằng công cụ tìm kiếm như Google.
            </p>
            <p>
                Nếu bạn chưa có một cái nhìn tổng quan qua công việc của chúng tôi, bạn hãy xem một vài ví dụ về những gì chúng ta đã làm. Cảm ơn :)
            </p>
        </div>
        <a id="readmore">Đọc tiếp +</a>
    </div>
</div>