    <div class="footer">
        <div class="container1">
            <div class="navFooter">
                <ul>
                    <li><a href="">Tw.</a></li>
                    <li><a href="">Fb.</a></li>
                    <li><a href="">Inst.</a></li>
                    <div class="clear"></div>
                </ul>
                <p>Bản quyền thuộc <span>© 2016 DWEB.VN</span></p>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>