<div class="nav" style="">
    <a id="btnNav">Menu</a>
    <ul>
        <li><a href="/">Trang chủ</a></li>
        <li><a href="/about">Về chúng tôi</a></li>
        <li><a>Kho giao diện</a>
            <?php
                $category = $this->newsCategory()->getCategories(['excludedIds' => 3]);
                if(count($category)){
            ?>
            <ul>
                <?php
                    foreach($category as $c){
                ?>
                <li><a href="<?= $c->getViewLink() ?>"><?= $c->getName() ?></a></li>
                <?php } ?>
            </ul>
            <?php } ?>
        </li>
        <li><a href="/blog">Chia sẻ</a></li>
        <li><a href="/contact">Liên hệ</a></li>
    </ul>
</div>
