<?= $this->render('layout/banner')?>
<?= $this->render('layout/slideflash') ?>
<div id="content">
	<div id="menu-pro">
		<p id="lb-parent">Hàng trăm mẫu giao diện website bán hàng cực đẹp và miễn phí</p>
		<p id="lb-child">Thay đổi tất cả các tính năng theo phong cách của bạn</p>
	</div>
	<div id="pro-ct">
		<?php for ($i=0;$i<=5;$i++){?>
				<div id="pro-ct-item1">
					<img src="/images/product/mau1.png" title="">
				</div>
			<?php }?>
	</div>

</div>
<?= $this->render('layout/partners') ?>
<!-- 	<div id="ct-left"> -->
<!-- 		<h4>Tin tức mới</h4> -->
<!-- 		<ul> -->
		<?php //for ($i=0;$i<8;$i++){?>
<!-- 			<li><a href="#">Thiết kế với công nghệ hiện đại và chuyên nghiệp nhất việt nam</a></li> -->
		<?php //}?>	
<!-- 		</ul> -->
<!-- 	</div> -->
<!-- 	<div id="ct-right"> -->
<!-- 		<div id="ct-ri-left"> -->
<!-- 			<p>Thiết kế các loại website với công nghệ hiện đại nhất phù hợp với mọi nhu cầu của bạn. -->
<!-- 				Có 9 lý do để bạn chọn TinhhoaWeb</p> -->
<!-- 			<ul> -->
<!-- 				<li id="a"><span>1</span>Thiết kế với công nghệ hiện đại và tiên tiến nhất</li> -->
<!-- 				<li><span>2</span>Thiết kế phù hợp với mọi yêu cầu của bạn</li> -->
<!-- 				<li id="a"><span>4</span>Thư viện module chức năng đa dạng, mạnh mẽ, dễ dùng</li> -->
<!-- 				<li><span>3</span>Hỗ trợ, chăm sóc khách hàng và tư vấn hiệu quả 24/7</li> -->
<!-- 				<li id="a"><span>5</span>Dữ liệu của bạn luôn an toàn và bảo mật</li> -->
<!-- 				<li><span>6</span>Tối ưu cho các máy tìm kiếm đặc biệt là Google</li> -->
<!-- 				<li id="a"><span>7</span>Giá cả hợp lý với mọi khách hàng</li> -->
<!-- 				<li><span>8</span>Thiết kế với công nghệ hiện đại</li> -->
<!-- 				<li id="a"><span>9</span>Thiết kế với công nghệ hiện đại</li> -->
<!-- 			</ul> -->
<!-- 		</div> -->
<!-- 		<div id="ct-ri-right"> -->
<!-- 			<h4>Hỗ trợ khách hàng</h4> -->
			<?php //for ($i=0; $i<7; $i++){?>
<!-- 			<div id="support2"> -->
<!-- 				<img src="images/us_sp.jpg" title="" class="img"/> -->
<!-- 				<div id="ct-support"> -->
<!-- 					<p id="name">Trương Hồng Hoàng</p> -->
<!-- 					<p><span>01676.274.056</span>&nbsp; -->
<!-- 						<a href="skype:hoang_tin3a2?chat" rel="nofollow"><i class="fa fa-skype"></i></a>&nbsp; -->
<!--  						<a href="#" onclick="window.location.href= 'ymsgr:SendIM?langtutinhtruong_1314';"> -->
<!-- 						<img src="http://opi.yahoo.com/online?u=langtutinhtruong_1314&amp;m=g&amp;t=1" border="0"/></a> -->
<!-- 					</p> -->
<!-- 				</div> -->
<!-- 			</div> -->
			<?php //}?>
			
<!-- 		</div> -->
<!-- 	</div> -->
