<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="f2">
                    <li>
                        <h2>THÔNG TIN LIÊN HỆ</h2>
                        <p>
                            TRỤ SỞ CHÍNH: 114 NGUYỄN DU – TP. HÀ NỘI<br/>
                            VĂN PHÒNG GIAO DỊCH: 107 HOÀNG NGÂN - THANH XUÂN - TP. HÀ NỘI<br/>
                            PHONE: 04.6670.8800.<br/>
                            HOT LINE : 094 242 1111<br/>
                            Mọi thắc mắc và khiếu nại vui lòng liên hệ : remmycollection2015@gmail.com<br/>
                            <strong>LIÊN HỆ MỞ ĐẠI LÝ : 0964 688 884</strong>
                        </p>
                    </li>
                    <li>
                        <h2>CÁC CHÍNH SÁCH</h2>
                        <a href="">CHÍNH SÁCH BẢO HÀNH VÀ ĐỔI SẢN PHẨM</a>
                        <a href="">CHÍNH SÁCH BẢO MẬT THÔNG TIN KHÁCH HÀNG</a>
                        <a href="">QUY ĐỊNH VỀ THANH TOÁN VÀ VẬN CHUYỂN</a>
                        <strong>CÔNG TY TNHH THỜI TRANG REMMY</strong>
                        MST: 0106478822<br/>
                        Cấp thay đổi lần 4 ngày 03/12/2014 tại Sở Kể Hoạch và Đầu Tư TP Hà Nội
                    </li>
                    <li>
                        <div class="social">
                            <h2><span>Follow Remmy</span></h2>
                            <a class="fb" href=""></a>
                            <a class="gg" href=""></a>
                            <a class="pt" href=""></a>
                            <a class="it" href=""></a>
                            <a class="yt" href=""></a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>